### ISSUE TITLE
Design Decisions Regarding None-Types For Parameter Validation(s) Steps

### ISSUE THREAD

**Issue by AFg6K7h4fhy2** [CDCgov/PyRenew#105]
## Goal

Determine design pattern for parameters of `None` type in the `_assert_sample_and_rtype` function (and possibly other functions)

## Context

From TPM:

> One uncertainty I had was the default behavior for the `_assert_sample_and_rtype` function generally. Is it a better pattern to not have a `skip_if_none` param and just instead have `_assert_sample_and_rtype` be able to handle these scenarios (`latent_admissions` v. `observation_process`, None or not None) internally?

From GVY: 

> That's a good question. I could be useful to post this as an issue/question. Right now, we have the NullRV class which somewhat deals with the None cases. Perhaps we could simply remove the option to skip checks as it should always be an instance of RandomVariable.

Code:

[see here for example usage](https://github.com/CDCgov/multisignal-epi-inference/blob/e261f16fd6233e3caf0706abf0938db846eceef6/model/src/pyrenew/model/rtinfectionsrenewalmodel.py#L128-L129)

```python
_assert_sample_and_rtype(latent_infections, skip_if_none=False)
_assert_sample_and_rtype(observation_process, skip_if_none=False)
```

[see here for the `_assert_sample_and_rtype`](https://github.com/CDCgov/multisignal-epi-inference/blob/e261f16fd6233e3caf0706abf0938db846eceef6/model/src/pyrenew/metaclass.py#L16-L86)

## Out of scope

- Complete redefinition of `_assert_sample_and_rtype`

**Comment by dylanhmorris** [comment]
Closing since the relevant validation patterns have now changed.
