### ISSUE TITLE
Improve access to tutorial files

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/PyRenew#122]
## Goal

In an ideal world, we can configure the Sphinx website's "edit this page on github" button to point to the files under `model/docs/*qmd` rather than to `docs/source/tutorials`.

## Context

- The tutorials section of the Sphinx website is built automatically during the website.yaml workflow.
- To avoid having multiple versions of the same file, we only have one copy of the cmd documents under `model/docs.`
- The website workflow generates the corresponding rst files and publishes the website with them.
- But the edit button points on the tutorials point to a non-existing location (b/c the files are created during the action and not available on the repo).
- The current package's version has a pre-commit hook that creates a placeholder for the rst files, indicating that the source code is located in `model/docs`.
- But this implementation is awkward.

See also https://github.com/CDCgov/multisignal-epi-inference/pull/118#discussion_r1602032476

## Required features

TBD

## Specifications

TBD

**Comment by dylanhmorris** [comment]
Closing as we've decided to go with #459 as the solution here
