### ISSUE TITLE
Data pipeline for NWSS

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/PyRenew#134]
Currently, there is no automatic data pipeline for processing the NWSS data. I am posting this here, but it should be relevant for @kaitejohnson as we will be sharing this data source.

cc @damonbayer @dylanhmorris @kgostic

**Comment by damonbayer** [comment]
Closing, as this should be part of https://github.com/CDCgov/pyrenew-covid-wastewater

**Comment by kaitejohnson** [comment]
I can write up an issue in that repo (should be an ETL for COVID and flu).
