### ISSUE TITLE
Instantiate CFA's Epidemia-For-Flu Model Via MSR

### ISSUE THREAD

**Issue by AFg6K7h4fhy2** [CDCgov/PyRenew#135]
## Goal

Verify that DHM's influenza forecasting repository `cfa-forecast-renewal-epidemia`, which utilizes `epidemia`, can be instantiated via MSR. 

## Context

Utility from the `multisignal-epi-inference` repository is derived from being able to modularly construct renewal processes. One renewal model that _should_ be able to be specified via MSR tools is the aforementioned `cfa-forecast-renewal-epidemia`. This port-over process, in expectation, might allow MSR developments to identify structural inadequacies or missing features and or usage capabilities. 

## Required Features

- Create `quarto` walk-through detailing the port-over steps and providing documentation. 
- Validate MSR implemented `cfa-forecast-renewal-epidemia` via simulation and fitting on NHSN data, which is the data `cfa-forecast-renewal-epidemia` has historically been used on.

## Out Of Scope

- Non-`epidemia` related MSR-implementations of renewal processes.
- `epidemia` beyond the scope of what's captured in `cfa-forecast-renewal-epidemia`.

## Related documents

- [Epidemia, website](https://imperialcollegelondon.github.io/epidemia/index.html)
- [Epidemia, GitHub](https://github.com/ImperialCollegeLondon/epidemia)
- [Epidemia, installation](https://imperialcollegelondon.github.io/epidemia/articles/install.html)
- [Epidemia, model description](https://imperialcollegelondon.github.io/epidemia/articles/model-description.html)
- [Epidemia, model implementation](https://imperialcollegelondon.github.io/epidemia/articles/model-implementation.html)

**Comment by seabbs** [comment]
> DHM's implementation of Epidemia.

I interpreted this as @dylanhmorris implementation of the tool `epidemia` but I know the meaning is the use of `epidemia` for flu forecasting. I imagine everyone is on the same page but perhaps worth a reword for clarity.

**Comment by AFg6K7h4fhy2** [comment]
@seabbs 

Thank you for the feedback, Sam. I've edited the issue. Wrt your first point, I think [that the target is a private repository] affected my wording, i.e I tried to cloak `cfa-forecast-renewal-epidemia`. Wrt the second point, this was simply a lack of detail on my end.

**Comment by AFg6K7h4fhy2** [comment]
The model has, more or less, been instantiated; it can be found here <https://github.com/CDCgov/pyrenew-flu-light>. Evaluate and further refinement in progress, see [this issue](https://github.com/CDCgov/pyrenew-flu-light/issues/1).
