### ISSUE TITLE
Investigate within-chain parallelization in `numpyro`

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/PyRenew#151]
## Goal
Understand what numpyro support exists for within-chain parallelization. 

## Details 
- The `plate` context can be used to mark conditionally independent sampling operations.
- Are there ways then to ask the compiler to parallelize things within a single MCMC chain, [as is possible in Stan](https://mc-stan.org/docs/stan-users-guide/parallelization.html)?

## See also
Related discussion in `EpiAware` https://github.com/CDCgov/Rt-without-renewal/issues/254

**Comment by dylanhmorris** [comment]
@seabbs reports that it looks possible with JAX but not implemented in numpyro's bundled samplers. So if we want/need this future the solution may be to do sampling via `blackjax` or `bayeux` (see also #361). 

In general, perhaps worth considering whether to separate PPL choice and sampler choice.

**Comment by seabbs** [comment]
*but that he does not think it is possible based on current evidence (I am heavily caveating as I really think it must be I just can't find any evidence).

**Comment by seabbs** [comment]
Okay some actual evidence: https://github.com/jax-ml/jax/issues/1408

**Comment by seabbs** [comment]
https://num.pyro.ai/en/latest/utilities.html#numpyro.util.set_host_devices

**Comment by damonbayer** [comment]
> https://num.pyro.ai/en/latest/utilities.html#numpyro.util.set_host_devices

We already use this to enable between-chain parallelization.
