### ISSUE TITLE
Consider using `numpyro.contrib.control_flow.scan` over `jax.lax.scan`

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/PyRenew#213]
Our use of `jax.lax.scan` has been fine so far, but the built-in `numpyro.contrib.control_flow.scan` offers additional features/compatibility with numpyro.

**Comment by dylanhmorris** [comment]
We have now mostly moved to this, but with the caveats to be explored in #444

**Comment by sbidari** [comment]
We use `jax.lax.scan` in the `Infection` classes, should these be switched to `numpyro.contrib.control_flow.scan`?
https://github.com/CDCgov/PyRenew/blob/3d06ab9aa285024b61f62046b996d12c8d764155/pyrenew/latent/infection_functions.py#L48

https://github.com/CDCgov/PyRenew/blob/3d06ab9aa285024b61f62046b996d12c8d764155/pyrenew/latent/infection_functions.py#L184

**Comment by dylanhmorris** [comment]
I think for deterministic scans we should probably stick with `jax.lax.scan` but let's discuss in #444
