### ISSUE TITLE
Create and name a subclass of `RandomVariable` to represent differenced timeseries

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/PyRenew#214]
## Motivation
Classes like `FirstDifferenceARProcess` below could be created by composing a representation of the differencing with a representation of the underlying timeseries of $n^\mathrm{th}$ differences. 

https://github.com/CDCgov/multisignal-epi-inference/blob/99cdf4272358d80966ce92007d896245d53d59e2/model/src/pyrenew/process/firstdifferencear.py#L12-L17

## Steps
- [ ] Choose a name for the class.
- [ ] Implement it.
- [ ] Reimplement the existing `FirstDifferenceARProcess` using it

**Comment by dylanhmorris** [comment]
Going to wait for #215 as it bears upon this.

**Comment by damonbayer** [comment]
Closed in https://github.com/CDCgov/PyRenew/pull/380
