### ISSUE TITLE
Feedback & feature request

### ISSUE THREAD

**Issue by zsusswein** [CDCgov/PyRenew#237]
Thanks for the nice demo today! I'm dumping this in a super-quick issue before I forget -- my self-interested feature request before future package user testing would be some code or guidance on pulling out Rt.

The first thing I would test would be to compare pyrenew's  Rt estimates to those from other models. Some copy and paste code or a method to pull Rt out & visualize (and make sure dates are lining up right!) would be helpful to speed that up.

**Comment by sbidari** [comment]
@zsusswein 

The code showing how to extract Rt and/or other model outputs is in this [tutorial](https://cdcgov.github.io/multisignal-epi-inference/tutorials/basic_renewal_model.html) (note: this is a separate tutorial from the one demo-ed few weeks ago).

After running the model, you can use `get_samples()` method from `numpyro.infer.MCMC` to extract samples
```{python}
posterior_samples = model.mcmc.get_samples()
```
returns a dict containing all posterior samples or
```{python}
Rt_samples = model.mcmc.get_samples()["Rt"]
```
to pull just the Rt.
