### ISSUE TITLE
Time units in InfectionSeedMethod and InfectionSeedingProcess

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/PyRenew#244]
[W]e agreed to measure `t_start` in fundamental units, not array units. Are `InfectionSeedingProcess`es and/or `InfectionSeedMethod`s going to be allowed to have non-fundamental units? If so, we potentially need a unit conversion operation here. If not, we need to enforce `t_unit = 1` for both.

My take: 
- it is worth allowing them to have non-fundamental units
- It is possibly worth enforcing that an `InfectionSeedingProcess` has _the same_ units as its associated `InfectionSeedMethod`

_Originally posted by @dylanhmorris in https://github.com/CDCgov/multisignal-epi-inference/pull/217#discussion_r1664529517_

**Comment by damonbayer** [comment]
Not planned, based on https://github.com/CDCgov/PyRenew/pull/441
