### ISSUE TITLE
First release of PyRenew library

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/PyRenew#283]
We need to create a versioned release of PyRenew, so that other repositories (https://github.com/CDCgov/multisignal-epi-inference/issues/382 & https://github.com/CDCgov/multisignal-epi-inference/issues/393) can rely on specific versions of the the library.

Prior to first release, we should

- [x] elevate the `model` directory to the root of the project
- [x] remove any use of the `pipeline` directory and mentions of it in the documentation
- [x] related issue: https://github.com/CDCgov/multisignal-epi-inference/issues/208
- [x] Rename https://github.com/CDCgov/multisignal-epi-inference/ to https://github.com/CDCgov/PyRenew

**Comment by AFg6K7h4fhy2** [comment]
I think this is gated (for reasons of robustness) by issues like #311 and #328. But I think "soonish" is a good answer.
