### ISSUE TITLE
Should SampledValues allow pytrees or only arrays?

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/PyRenew#315]
> Good question. I would say yes, keep things as ArrayLike objects, but pytrees should be, in principle, OK. Since I'm making the SampledValue a namedtuple, I'm taking this out and we can leave it for a later discussion if we want to enforce a type.

_Originally posted by @gvegayon in https://github.com/CDCgov/multisignal-epi-inference/pull/262#discussion_r1690502708 Question by @dylanhmorris_

**Comment by damonbayer** [comment]
Related: https://github.com/CDCgov/multisignal-epi-inference/issues/308

**Comment by damonbayer** [comment]
Closed in https://github.com/CDCgov/PyRenew/pull/441
