### ISSUE TITLE
Running list of time-aware components

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/PyRenew#320]
With #262 closing soon (🙏🏼), we will be able to leverage the time information potentially attached to sampled values. This issue should serve as a way to track+discuss components of `pyrenew` that should leverage this. Here is as of July 25th:

- [ ] `PeriodicBroadcaster`
- [ ] `PeriodicEffect`

**Comment by damonbayer** [comment]
If this is meant to be an ongoing discussion (i.e. not an issue that will be closed), I recommended moving to https://github.com/CDCgov/multisignal-epi-inference/discussions

**Comment by gvegayon** [comment]
Flagging this for awareness, @damonbayer. I would close this issue.
