### ISSUE TITLE
Refactor AR process

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/PyRenew#328]
We should clean up https://github.com/CDCgov/multisignal-epi-inference/blob/main/model/src/pyrenew/process/ar.py to reflect recent design decisions. This work should be similar to the work done in https://github.com/CDCgov/multisignal-epi-inference/pull/275.

We should also look around at other examples to see if we can learn any lessons:

- https://forum.pyro.ai/t/ar-p-in-numpyro/2671
- https://juanitorduz.github.io/arma_numpyro/
- https://num.pyro.ai/en/stable/examples/ar2.html

**Comment by damonbayer** [comment]
Also related: https://github.com/CDCgov/multisignal-epi-inference/issues/214

**Comment by dylanhmorris** [comment]
https://github.com/CDCgov/multisignal-epi-inference/pull/262#discussion_r1693486666
