### ISSUE TITLE
Remove `DeterministicProcess` class

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/PyRenew#335]
> Made an attempt in 9ff9dea but I increasingly think we should get rid of the `DeterministicProcess` class, as I think it should be replaced by other more time-aware ways of handling temporal broadcasting of values. Beyond the scope of this PR, though.

_Originally posted by @dylanhmorris in https://github.com/CDCgov/multisignal-epi-inference/pull/262#discussion_r1693508848_

**Comment by damonbayer** [comment]
Closed in https://github.com/CDCgov/PyRenew/pull/441
