### ISSUE TITLE
Incorrect convolve mode in `hospitaladmissions.py`

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/PyRenew#385]
We should use `mode="valid"` to ensure the output reflects the entire `infection_to_admission_interval` being used.

https://github.com/CDCgov/multisignal-epi-inference/blob/main/model/src/pyrenew/latent/hospitaladmissions.py#L189-L193

I believe these lines should be replaced with

```python
        latent_hospital_admissions = jnp.convolve(
            latent_hospital_admissions_raw,
            infection_to_admission_interval.value,
            mode="valid",
        )
```

**Comment by dylanhmorris** [comment]
I think the previous version was to allow the kind of behavior we've now decided to forbid. But I agree with forbidding it, at least by default.

**Comment by damonbayer** [comment]
The issue is actually more with the post-convolve indexing, but this change makes it easier to avoid that error.

**Comment by damonbayer** [comment]
With `mode="full"` you will get results that implicitly pad the arrays with with 0's. When using `mode="valid"`, this does not happen.

With `mode="full"`, you then have to slice the head and the tail of the resulting array to get the desired output. With `mode="valid"` you only need the tail.

**Comment by sbidari** [comment]
> With `mode="full"`, you then have to slice the head and the tail of the resulting array to get the desired output. With `mode="valid"` you only need the tail.

The current implementation only includes slicing one end of the array resulting from convolution.


Using `mode = "valid"` results in `latent_hospital_admissions` array smaller than desired shape i.e `latent_hospital_admissions_raw.shape[0]`. Did you want to say `mode = "same"`?

**Comment by damonbayer** [comment]
> Using `mode = "valid"` results in `latent_hospital_admissions` array smaller than desired shape i.e `latent_hospital_admissions_raw.shape[0]`. Did you want to say `mode = "same"`?

No, the "valid" mode is correct. The desired shape in the end should be the length of the observed cases. We can do that here or later on in the "model" code.

**Comment by damonbayer** [comment]
> But convolve `mode = "valid"` yields `latent_hospital_admissions` array with length smaller than `observed_hosp_admissions`.

What are the lengths of the relevant quantities?

**Comment by sbidari** [comment]
> > But convolve `mode = "valid"` yields `latent_hospital_admissions` array with length smaller than `observed_hosp_admissions`.
> 
> What are the lengths of the relevant quantities?

```
      latent_hospital_admissions = jnp.convolve(
          latent_hospital_admissions_raw,
          infection_to_admission_interval.value,
          mode="full",
      )
latent_hospital_admissions.shape 
# (105, )
```

```
      latent_hospital_admissions = jnp.convolve(
          latent_hospital_admissions_raw,
          infection_to_admission_interval.value,
          mode="valid",
      )
latent_hospital_admissions.shape 
# (51, )

observed_hosp_admissions.shape
# (90, )
```
