### ISSUE TITLE
`randomvariable` module

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/PyRenew#392]
I think there are enough concrete but generic `RandomVariable`s that they should have their own module rather than living in `metaclass.py`, especially since they aren't actually abstract

Candidates for this include `DeterministicVariable`, `DistributionalRV`, `TransformedRandomVariable`, etc.

^ This list also makes clear that we should also standardize their suffixes (versus having all of `Variable`, `RandomVariable`, and `RV`.

**Comment by dylanhmorris** [comment]
@CDCgov/multisignal-epi-inference-devs

**Comment by damonbayer** [comment]
My vote is for `DeterministicVariable`, `DistributionalVariable`, and `TransformedVariable`.

**Comment by dylanhmorris** [comment]
I agree

**Comment by gvegayon** [comment]
I would say `Variable` instead of `RV`, that way we avoid confusing people with degenerate RVs.
