### ISSUE TITLE
Correctness unit tests for pyrenew.process

### ISSUE THREAD

**Issue by ghost** [CDCgov/PyRenew#4]
## Goal

Unit tests to verify correctness of `pyrenew` stochastic processes.

## Context

Currently, the only unit tests for stochastic processes verify that they can be instantiated and sampled. We would also like to verify that they correctly implement what they say they implement (e.g. a Normal random walk is actually a Normal random walk; an AR(1) process is actually an AR(1) process).

## Required features / Specifications
- Tests that assess whether samples produced by the `sample()` method are approximately distributed according to the target distribution
- Tests that check that `log_prob()` values produced when using the processes for inference.

## Out of scope
- Other unit tests
- Improved documentation for processes

Ref: https://github.com/cdcent/cfa-multisignal-renewal/issues/61
author: @dylanhmorris

**Comment by dylanhmorris** [comment]
There is now enough progress on this in general that any further issues should be specific to particular classes.
