### ISSUE TITLE
Future of PyRenew container?

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/PyRenew#401]
Noting that our current Dockerfile is out of date with respect to file structure.

**Comment by dylanhmorris** [comment]
I think we should do away with it for now and create a new one if and when it is needed.

**Comment by damonbayer** [comment]
I have deleted the github package using these instructions https://docs.github.com/en/packages/learn-github-packages/deleting-and-restoring-a-package#deleting-an-entire-package
