### ISSUE TITLE
Make target for building docs with sphinx

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/PyRenew#413]
We should have a make target for building the docs using sphinx. It should be used in the github action for building the website.

**Comment by damonbayer** [comment]
This could be done in conjunction with https://github.com/CDCgov/PyRenew/issues/231

**Comment by AFg6K7h4fhy2** [comment]
> This could be done in conjunction with #231

Added Dylan on here given this statement.

**Comment by dylanhmorris** [comment]
@damonbayer can you clarify whether you want this in the top-level project directory or in the `docs` subdirectory? Sphinx has its own standard Makefile for the `docs` subdirectory. We could just reference that from the top-level, depending on how Harmful we Consider Recursive Make.

**Comment by damonbayer** [comment]
@dylanhmorris I don't have any opinion on the location. I just want a one line command that lets you see the rendered docs locally. Apologies if that already exists, and I missed it.

**Comment by dylanhmorris** [comment]
I think for now let's go with `make html` within `docs`, which as of 3a3a566 will render the tutorials to markdown (provided you've deleted the placeholders and/or modified the `.qmd` source) and then render the website as html locally via `sphinx-build`. We could tweak it a bit more to handle the placeholders better, but I'd rather just do #459

**Comment by dylanhmorris** [comment]
Addressed by #457
