### ISSUE TITLE
Consistent Behavior With UTF-8 Encoding

### ISSUE THREAD

**Issue by AFg6K7h4fhy2** [CDCgov/PyRenew#420]
At the beginning of some files, e.g. <https://github.com/CDCgov/PyRenew/blob/main/pyrenew/latent/infections.py>, there exists `# -*- coding: utf-8 -*-`. Other files, e.g. <https://github.com/CDCgov/PyRenew/blob/main/pyrenew/datasets/generation_interval.py>, do not possess this feature.

According to this StackOverflow thread (<https://stackoverflow.com/questions/13807748/when-to-use-utf8-as-a-header-in-py-files>), "UTF-8 is the default" for Python3 and "Some Windows editors don't have it by default. It won't hurt to declare it, and some editors may use it.". 

Should we ensure all `pyrenew` files having this attribute or remove it?

**Comment by damonbayer** [comment]
I think we should remove it everywhere.
