### ISSUE TITLE
Update ARProcess and InfectionInitializationProcess to handle batched input

### ISSUE THREAD

**Issue by sbidari** [CDCgov/PyRenew#423]
Currently, `ARProcess` and `InfectionInitializationProcess` (and possibly others) require scalar inputs which prevents these from being used with `numpyro.plate`.

This emerged while trying to use `numpyro.plate` to calculate site-level dynamics for each site in https://github.com/CDCgov/pyrenew-covid-wastewater/issues/7

I am also open to other possible ways of handling this and maybe worth having a discussion about the best way to do it. For reference, I tried using a `for` loop but that required modifying the `name` arguments of `RandomVariables`. @dylanhmorris mentioned potentially using `jax.lax.scan`

**Comment by dylanhmorris** [comment]
Minimal reproducible example? Which inputs are causing plate to object?

**Comment by dylanhmorris** [comment]
Also, what if you define the instatiate the process outside the plate but `sample()` within the plate?

**Comment by sbidari** [comment]
`numpyro.plate` vectorizes `noise_sd` for the "plate size" (not sure if this is the correct term) but `ARProcess` expects `noise_sd` input to be a scalar

**Comment by sbidari** [comment]
This reproduces the issue with using `ARProcess`

```{python}
import numpyro
from pyrenew.process import ARProcess
from pyrenew.randomvariable import DistributionalVariable
from pyrenew.metaclass import Model
import numpyro.distributions as dist

class my_model(Model):
    def __init__(
            self, 
            autoreg_rt_site_rv,
            sigma_rt_rv,
            rtu_site_ar_proc,
            ):
        
        self.autoreg_rt_site_rv = autoreg_rt_site_rv
        self.sigma_rt_rv = sigma_rt_rv
        self.rtu_site_ar_proc = rtu_site_ar_proc

    def validate(self):
        pass

    def sample(self, n_weeks):
        with numpyro.plate("subpop", 5):
            autoreg_rt_site =self.autoreg_rt_site_rv()[0].value
            sigma_rt = self.sigma_rt_rv()[0].value

            rtu_site_ar_init_rv = DistributionalVariable("rtu_site_ar_init",dist.Normal(0,1))

            rtu_site_ar_init = rtu_site_ar_init_rv()[0].value

            rtu_site_ar_weekly = self.rtu_site_ar_proc(
                n=n_weeks,
                init_vals=rtu_site_ar_init,
                autoreg=autoreg_rt_site,
                noise_sd=sigma_rt,
            )
            return rtu_site_ar_weekly


autoreg_rt_site_rv = DistributionalVariable("autoreg_rt", dist.Beta(1,1))
sigma_rt_rv = DistributionalVariable("sigma_rt", dist.TruncatedNormal(1,1,low=0))
rtu_site_ar_proc = ARProcess(noise_rv_name="rtu_ar_proc")

model1 = my_model(autoreg_rt_site_rv,sigma_rt_rv,rtu_site_ar_proc)

with numpyro.handlers.seed(rng_seed=5):
    model1.sample(n_weeks=10)
```
one line error summary
```{python}
## ValueError: noise_sd must be a scalar. Got [0.40856445 0.3173288  1.530092   0.78180265 1.627873  ]
```

**Comment by damonbayer** [comment]
This is blocking https://github.com/CDCgov/pyrenew-covid-wastewater/issues/7

**Comment by dylanhmorris** [comment]
Suggest splitting this into sub-issues for the two RV classes.

**Comment by AFg6K7h4fhy2** [comment]
Maybe a second `numpyro.plate` is needed here for timepoint?

**Comment by AFg6K7h4fhy2** [comment]
For the warning, wo/ `with numpyro.plate("timepoint", n_timepoints):` above

```python
mean_infec = i0 * jnp.exp(
    rate * jnp.expand_dims(jnp.arange(n_timepoints), 1)
)
numpyro.sample("obs", dist.Poisson(mean_infec), obs=y)
```

out:

```
db_plate_eg.py:30: UserWarning: Missing a plate statement for batch dimension -2 at site 'obs'. You can use `numpyro.util.format_shapes` utility to check shapes at all sites of your model.
  mcmc.run(rng_key, y=y_data)
sample: 100%|████████████████████████████████████| 1500/1500 [00:01<00:00, 1042.99it/s, 63 steps of size 6.52e-02. acc. prob=0.89]

                mean       std    median      5.0%     95.0%     n_eff     r_hat
     i0[0]      1.00      0.06      1.00      0.91      1.09    472.95      1.00
     i0[1]      1.99      0.11      1.99      1.80      2.16    394.08      1.00
     i0[2]      2.96      0.13      2.96      2.75      3.17    524.65      1.00
   rate[0]      1.10      0.01      1.10      1.09      1.11    466.99      1.00
   rate[1]      1.01      0.01      1.01      1.00      1.02    401.20      1.00
   rate[2]      1.00      0.01      1.00      0.99      1.01    528.82      1.00

Number of divergences: 0
```

and __w/__ the `with numpyro.plate("timepoint", n_timepoints):`

```
sample: 100%|████████████████████████████████████| 1500/1500 [00:01<00:00, 1127.89it/s, 63 steps of size 6.52e-02. acc. prob=0.89]

                mean       std    median      5.0%     95.0%     n_eff     r_hat
     i0[0]      1.00      0.06      1.00      0.91      1.09    472.95      1.00
     i0[1]      1.99      0.11      1.99      1.80      2.16    394.08      1.00
     i0[2]      2.96      0.13      2.96      2.75      3.17    524.65      1.00
   rate[0]      1.10      0.01      1.10      1.09      1.11    466.99      1.00
   rate[1]      1.01      0.01      1.01      1.00      1.02    401.20      1.00
   rate[2]      1.00      0.01      1.00      0.99      1.01    528.82      1.00

Number of divergences: 0
```

**Comment by AFg6K7h4fhy2** [comment]
Modified, for no warning:

```python
def my_model(y):
    with numpyro.plate("subpop", n_subpops):
        rate = numpyro.sample("rate", dist.HalfNormal())
        i0 = numpyro.sample("i0", dist.HalfNormal())
        with numpyro.plate("timepoint", n_timepoints):
            mean_infec = i0 * jnp.exp(
                rate * jnp.expand_dims(jnp.arange(n_timepoints), 1)
            )
            numpyro.sample("obs", dist.Poisson(mean_infec), obs=y)
```

**Comment by damonbayer** [comment]
Thanks @AFg6K7h4fhy2. I'm glad we have something working without a warning, but this all feels a bit funny to me. In particular, it seems like we should be able to come up with a solution that doesn't require the time series to be of equal length.

**Comment by AFg6K7h4fhy2** [comment]
> Thanks @AFg6K7h4fhy2. I'm glad we have something working without a warning, but this all feels a bit funny to me. In particular, it seems like we should be able to come up with a solution that doesn't require the time series to be of equal length.

Agree. I'm not going to investigate the `dim=` option right now, but hopefully there is something there that supports our ends better.

**Comment by damonbayer** [comment]
After discussing with @dylanhmorris, we plan to avoid working with ragged arrays and indexing and implement solutions with broadcasting instead.

**Comment by damonbayer** [comment]
After discussing with @dylanhmorris, we have agreed on
 
1. Models should accept [tidy data](https://r4ds.had.co.nz/tidy-data.html). (Ex: time, location, count columns)
2. Internal replication of model components should be achieved with `numpyro.plate`s (Ex `with numpyro.plate("location", n_locations)`.
3. Latent computations should be done internal to `plate`s and/or using broadcasting when possible. This may result in cases where we compute "unused" variables (Ex. location 1 has observations at 20 timepoints and location 2 has observations at 10 timepoints. We will compute the full latent time series for both locations).
5. Observation samples should occur outside of `plate`s using indexing based on the tidy data.

**Comment by damonbayer** [comment]
Updated example based on above recommendations is below. A bit unclear about what this implies for the rest of PyRenew. I think we may need to stick in some `atleast_1d` calls throughout.

```python
import jax.numpy as jnp
import numpy as np
import numpyro
import numpyro.distributions as dist
from jax import random
from numpyro.infer import MCMC, NUTS
import polars as pl
import string

n_groups = 4
rates = 1 + jnp.pow(10.0, -(jnp.arange(n_groups) + 1))
n_timepoints = jnp.arange(n_groups) + 10
i0s = jnp.arange(n_groups) + 1


input_data = pl.DataFrame(
    {
        "group": pl.Series(np.array(list(string.ascii_lowercase))[
            np.repeat(np.arange(n_groups), n_timepoints)
        ], dtype = pl.Categorical),
        "time": np.concatenate(
            [np.arange(n_timepoint) for n_timepoint in n_timepoints]
        ),
        "obs": np.concatenate(
            [
                i0 * np.exp(rate * np.arange(n_timepoints))
                for rate, i0, n_timepoints in zip(rates, i0s, n_timepoints)
            ]
        ),
    }
)#.filter(~((pl.col("group") == "a") & (pl.col("time") == 4)))

y_group = input_data["group"].to_numpy()
y_time = input_data["time"].to_numpy()
y_obs = input_data["obs"].to_numpy()


# This would be done at modle instantiation:
y_group_ind = input_data["group"].to_physical().to_numpy()
y_time_max = input_data["time"].max()

def my_model(y_group, y_time, y_obs):
    with numpyro.plate("group", n_groups):
        rate = numpyro.sample("rate", dist.HalfNormal())
        i0 = numpyro.sample("i0", dist.HalfNormal())
        mean_infec = i0 * jnp.exp(rate * jnp.arange(y_time_max+1)[:, jnp.newaxis])
        
    numpyro.sample("obs", dist.Poisson(mean_infec[y_time, y_group]), obs=y_obs)

# Posterior Sampling
nuts_kernel = NUTS(my_model, find_heuristic_step_size = True)
mcmc = MCMC(nuts_kernel, num_warmup=500, num_samples=1000)
rng_key = random.PRNGKey(0)
mcmc.run(rng_key, y_group = y_group_ind, y_time = y_time, y_obs = y_obs)

# Check results
mcmc.print_summary()
```

**Comment by dylanhmorris** [comment]
Infection initialization process handled by #432, correct @damonbayer? Or does `InitializeInfectionsZeroPad` also need reworking etc?

**Comment by damonbayer** [comment]
> Was the Infection initialization process part of this issue handled by #432, @damonbayer? Or do other initialization schemes such as `InitializeInfectionsZeroPad` also need reworking?

It's a non-trivial fix. I would like to first consider removing the `InfectionInitializationMethod` class and the `InitializeInfectionsFromVec` and `InitializeInfectionsZeroPad` functions.

**Comment by damonbayer** [comment]
I think the `initialize` functions should just be `RandomVariable`s. There shared interface was not very elegant and somewhat confusing. `InitializeInfectionsFromVec` can just be a `DeterministicVariable`.

**Comment by damonbayer** [comment]
Partially closed by https://github.com/CDCgov/PyRenew/pull/432

**Comment by damonbayer** [comment]
Fully closed by https://github.com/CDCgov/PyRenew/pull/439
