### ISSUE TITLE
Create a CensoredNormal distribution

### ISSUE THREAD

**Issue by sbidari** [CDCgov/PyRenew#427]
The observation process for the log viral genome concentration in wastewater follow a censored normal distribution with concentration below the level of detection (LOD) censored. 
We can use @dylanhmorris's implementation of the censored normal distribution [here](https://github.com/dylanhmorris/host-viral-determinants/blob/42d4b47ad9e7d774bb8a9891ee78086eaaf1409a/src/distributions.py#L89-L144).

I am wondering if the censored normal distribution in `PyRenew` should inherit from the `RandomVariable` class instead of `numpyro.distributions.Distribution` so that it can be "time-aware" like all other randomvariables. Thoughts? @damonbayer @dylanhmorris @AFg6K7h4fhy2

**Comment by dylanhmorris** [comment]
I would advocate for a full distribution and then using `DistributionalVariable` when we want to treat it as an RV
