### ISSUE TITLE
Edit README To Include Instantiated Models

### ISSUE THREAD

**Issue by AFg6K7h4fhy2** [CDCgov/PyRenew#429]
There are PyRenew models that now exist in external repositories and, while referenced in Issues and PRs, it also makes sense to clearly indicate where these models exist. The author's expectation is that some people might go to this repository first, when looking for any of the PyRenew-dependent repositories, and not readily be able to find these external PyRenew models.

**Comment by damonbayer** [comment]
Great idea!
