### ISSUE TITLE
Update `quarto_python_formatter.py` to use `ruff` (and possibly find a new home for it)

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/PyRenew#472]
As of https://github.com/CDCgov/PyRenew/pull/467, we no longer us `black` for formatting and instead use `ruff`.

**Comment by damonbayer** [comment]
@gvegayon has expressed interest in having this in https://github.com/CDCgov/cfa-actions

**Comment by dylanhmorris** [comment]
> @gvegayon has expressed interest in having this in https://github.com/CDCgov/cfa-actions

That seems reasonable to me!
